#!/usr/bin/env php
<?php
$usage="csTune file.cs\n";
if($argc==1)exit($usage);
$cs=$argv[$argc-1];
require("csRead.php");
foreach($cs as &$c){
	if($c[0]==$c[2])$c[1]=(1+$c[1])/2;
	else $c[1]=$c[1]/2;
	unset($c);
}
require("csWrite.php");
?>
