#!/usr/bin/php
<?php
/**
* transpose the matrix in a mat file(the format of mat file is defined in cluto)
* the output's indexes of rows and columns start from zero.
*/
ini_set("memory_limit","1000M");
$file=$argv[1];
$matrix=file($file,FILE_IGNORE_NEW_LINES);
$option=array_shift($matrix);
$option=preg_split("/\s+/",trim($option));

if($option[2]){
	$rows=array();
	while(list($k,$v)=each($matrix)){
		$v=preg_split("/\s+/",trim($v));
		while(list($k1,$v1)=each($v)){
			$v1--;
			list($k2,$v2)=each($v);
			$rows[$v1][$k]=$v2;
		}
 	}
    for($i=0;$i<$option[1];$i++){
        for($j=0;$j<$option[0];$j++){
            echo $rows[$i][$j]?$rows[$i][$j]:0," ";
        }
        echo "\n";
    }
}else{
    $rows=array();
    while(list($k,$v)=each($matrix)){
        $v=preg_split("/\s+/",trim($v));
        while(list($kk,$vv)=each($v)){
            $rows[$kk][$k]=$vv;
        }
    }
    while(list($i,$row)=each($rows)){
        while(list($j,$v)=each($row)){
            echo $v," ";
        }
        echo "\n";
    }
}
?>
